#!/usr/bin/env python3
"""NodeKit - Simple proxy subscription to Clash config converter."""

import argparse
import base64
import re
import sys
import urllib.request
from urllib.error import URLError


def fetch_subscription(url: str) -> str:
    """Download subscription content."""
    req = urllib.request.Request(url, headers={'User-Agent': 'ClashForWindows/0.19.23'})
    with urllib.request.urlopen(req, timeout=15) as resp:
        return resp.read().decode('utf-8', errors='ignore')


def decode_base64(data: str) -> str:
    """Decode Base64 with padding fix."""
    data = data.strip()
    pad = 4 - len(data) % 4
    if pad != 4:
        data += '=' * pad
    return base64.urlsafe_b64decode(data).decode('utf-8', errors='ignore')


def parse_ss_node(ss_url: str) -> dict | None:
    """Parse ss:// URL into node dict."""
    # ss://BASE64(method:password)@server:port#name
    m = re.match(r'^ss://([^@]+)@([^:]+):(\d+)#(.+)$', ss_url)
    if not m:
        return None
    
    method_password_b64 = m.group(1)
    server = m.group(2)
    port = int(m.group(3))
    name = urllib.request.unquote(m.group(4))
    
    try:
        method_password = decode_base64(method_password_b64)
        method, password = method_password.split(':', 1)
    except Exception:
        # Try plain text (some subs use plain method:password)
        if ':' in method_password_b64:
            method, password = method_password_b64.split(':', 1)
        else:
            return None
    
    return {
        'name': name,
        'type': 'ss',
        'server': server,
        'port': port,
        'cipher': method,
        'password': password,
    }


def nodes_to_clash_yaml(nodes: list[dict]) -> str:
    """Generate minimal Clash YAML config."""
    lines = [
        '# Clash config generated by NodeKit',
        'mixed-port: 7890',
        'allow-lan: false',
        'mode: rule',
        'log-level: info',
        'ipv6: false',
        '',
        'proxies:',
    ]
    for node in nodes:
        lines.append(f"  - {{name: \"{node['name']}\", type: {node['type']}, server: {node['server']}, port: {node['port']}, cipher: {node['cipher']}, password: \"{node['password']}\"}}")
    
    lines.append('')
    lines.append('proxy-groups:')
    lines.append('  - {name: "PROXY", type: select, proxies: ["DIRECT", %s]}' % ', '.join(f'"{n["name"]}"' for n in nodes))
    
    lines.append('')
    lines.append('rules:')
    lines.append('  - MATCH,PROXY')
    
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description='NodeKit - Convert subscription to Clash config')
    parser.add_argument('--url', required=True, help='Subscription URL')
    parser.add_argument('-o', '--output', default='config.yaml', help='Output file (default: config.yaml)')
    args = parser.parse_args()
    
    print(f"📡 Fetching subscription from {args.url[:60]}...")
    try:
        raw = fetch_subscription(args.url)
    except URLError as e:
        print(f"❌ Failed to fetch: {e}", file=sys.stderr)
        sys.exit(1)
    
    print(f"📦 Downloaded {len(raw)} bytes")
    
    # Try decode as base64
    try:
        decoded = decode_base64(raw)
    except Exception:
        decoded = raw
    
    # Split into lines and parse
    nodes = []
    for line in decoded.strip().split('\n'):
        line = line.strip()
        if not line or not line.startswith('ss://'):
            continue
        node = parse_ss_node(line)
        if node:
            nodes.append(node)
    
    if not nodes:
        print("❌ No valid SS nodes found. Only SS protocol is supported in this version.", file=sys.stderr)
        sys.exit(1)
    
    print(f"✅ Parsed {len(nodes)} SS nodes")
    for n in nodes:
        print(f"   • {n['name']} ({n['server']}:{n['port']})")
    
    yaml_content = nodes_to_clash_yaml(nodes)
    
    with open(args.output, 'w', encoding='utf-8') as f:
        f.write(yaml_content)
    
    print(f"\n💾 Config saved to {args.output}")
    print("🚀 Import this file into Clash/Clash Verge and you're good to go!")


if __name__ == '__main__':
    main()
